server:
  port: 8080

spring:
  main:
    banner-mode: off

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true


  sql:
    init:
      mode: always
      schema-locations: classpath:/db/schema.sql
      data-locations: classpath:/db/data.sql

variables:
  jwtSecret: "secret"
  jwtExpirationMS: 864_000_000